<?php echo $this->doctype(); ?>
<html xmlns = "http://www.w3.org/1999/xhtml" xml:lang = "es" lang = "es">
	<head>
		<?php echo $this->headMeta()."\n"; ?>
		<?php echo $this->headTitle()."\n"; ?>		
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/css/Main.css")."\n"; ?>
		<?php echo $this->jQuery()->addStylesheet($this->baseUrl(). "/css/jquery-ui-1.8.5.custom.css")
								  ->setLocalPath($this->baseUrl(). "/js/jquery-1.4.2.min.js")
								  ->setUiLocalPath($this->baseUrl()."/js/jquery-ui-1.8.5.custom.min.js")
								  ->enable()
								  ->uiEnable();?>
	</head>
	<body background="<?php echo $this->baseUrl()."/image/bg.gif"?>" >
		<div class="frame">
			<div id="header">
			<?php echo $this->header($this->baseUrl())?>
			</div>
			<div id="menuBar">
			<?php echo $this->menuBar($this->baseUrl())?>
			</div>
			<div id="content">
				<h1><?php echo $this->escape($this->title); ?></h1>
				<?php echo $this->layout()->content; ?>
			</div>
			<div id="footer">
			<?php echo $this->footer($this->baseUrl())?>
			</div>
		</div>
	</body>
</html>
