<?php echo $this->doctype(); ?>
<html xmlns = "http://www.w3.org/1999/xhtml" xml:lang = "es" lang = "es">
	<head>
		<?php echo $this->headMeta()."\n"; ?>
		<?php echo $this->headTitle()."\n"; ?>		
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/css/biblioteca.css")."\n"; ?>
	</head>
	<body>
		<div id="header">
		<?php echo $this->header()?>
		</div>
		<div id="content">
			<h1><?php echo $this->escape($this->title); ?></h1>
			<?php echo $this->layout()->content; ?>
		</div>
		<div id="footer">
		<?php echo $this->footer()?>
		</div>
	</body>
</html>
