<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

</style>
<?php echo $this->mensaje ;?>
<?php $this->jQuery()->addOnLoad('alert("Hola, Mundo.");'); ?>
Pick your date:<?php echo $this->datePicker("dp1",
                                             '',
                                             array(
                                                'defaultDate' =>
                                                    date('Y/m/d', time())));?>


<?php echo $this->form ;?>

