<p>¿Estás seguro que quieres borrar el la persona 
'<?php echo $this->escape($this->persona['nombre']); ?>' por 
'<?php echo $this->escape($this->persona['apellidos']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'borrar')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->persona['id']; ?>" />
		<input type="submit" name="del" value="Si" />
		<input type="submit" name="del" value="No" />
	</div>
</form>