<p>¿Estás seguro que quieres borrar el libro 
'<?php echo $this->escape($this->libro['titulo']); ?>' por 
'<?php echo $this->escape($this->libro['autor']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'borrar')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->libro['id']; ?>" />
		<input type="submit" name="del" value="Si" />
		<input type="submit" name="del" value="No" />
	</div>
</form>