<?php
class Form_Pasantia extends Zend_Form{

public $elementsDecorators = array(
        'ViewHelper',
        'Errors',
        array(array('data' => 'HtmlTag'), array('tag' => 'td', 'class' => 'element')),
        array('Label', array('tag' => 'td')),
        array(array('row' => 'HtmlTag'), array('tag' => 'tr')),
		);

		public $buttonsDecorators = array(
			'ViewHelper',
			array(array('data' => 'HtmlTag'), array('tag' => 'td', 'class' => 'button')),
			//array(array('label' => 'HtmlTag'), array('tag' => 'td', 'placement' => 'prepend')),
			//array(array('row' => 'HtmlTag'), array('tag' => 'tr')),
		);

		public function loadDefaultDecorators()
    {
        $this->setDecorators(array(
            'FormElements',
            array('HtmlTag', array('tag' => 'table')),
            'Form',
        ));
    }

	public function __construct($options = null){
		parent::__construct($options);
		
		
		
		
		$this->setName('pasantia');
		 $id = new Zend_Form_Element_Hidden('id'); 
		 
		$idPersona = new Zend_Form_Element_Text('idPersona');
		$idPersona->setLabel('Persona Id')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$ano = new Zend_Form_Element_Text('ano');
		$ano->setLabel('Ano')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$periodo = new Zend_Form_Element_Select('periodo');
		$periodo->setLabel('Periodo')
		->setDecorators($this->elementsDecorators)	
		->setmultioptions(array('I' =>'I', 'II'=>'II'))
		->setRequired(true);
		
		$semestre = new Zend_Form_Element_Select('semestre');
		$semestre->setLabel('Semestre')
		->setDecorators($this->elementsDecorators)
		->setmultioptions(array('1' =>'I', '2'=>'II','3' =>'III', '4'=>'IV','5' =>'V', '6'=>'VI','7' =>'VII', '8'=>'VIII','9' =>'IX', '10'=>'X','NA' => 'NA'))
		->setRequired(true);
		
		$pais_origen = new Zend_Form_Element_Select('pais_origen');
		$pais_origen->setLabel('Pais de Origen')
		->setDecorators($this->elementsDecorators)
		->setmultioptions(array('Afganistan'=>'Afganistan',
								    'Islas Aland '=>'Islas Aland',
									'Albania'=>'Albania',
									'Argelia'=>'Argelia',
									'Samoa Americana'=>'Samoa Americana',
									'Andorra'=>'Andorra',
									'Angola'=>'Angola',
									'Anguila'=>'Anguila',
									'Antartida'=>'Antartida',
									'Antigua y Barbuda'=>'Antigua y Barbuda',
									'Argentina'=>'Argentina',
									'Armenia'=>'Armenia',
									'Aruba'=>'Aruba',
									'Australia'=>'Australia',
									'Austria'=>'Austria',
									'Azerbaiyan'=>'Azerbaiyan',
									'Bahamas'=>'Bahamas',
									'Bahréin'=>'Bahréin',
									'Bangladesh'=>'Bangladesh',
									'Barbados'=>'Barbados',
									'Bielorusia'=>'Bielorusia',
									'Bélgica'=>'Bélgica',
									'Belice'=>'Belice',
									'Benin'=>'Benin',
									'Bermuda'=>'Bermuda',
									'Butan'=>'Butan',
									'Bolivia'=>'Bolivia',
									'Bosnia y Herzegovina'=>'Bosnia y Herzegovina',
									'Botswana'=>'Botswana',
									'Isla Bouvet'=>'Isla Bouvet',
									'Brasil'=>'Brasil',
									'Territorio Britanico en el Océano Indico'=>'Territorio Britanico en el Océano Indico',
									'Islas Virgenes (Reino Unido)'=>'Islas Virgenes (Reino Unido)',
									'Brunei'=>'Brunei',
									'Bulgaria'=>'Bulgaria',
									'Burkina Faso'=>'Burkina Faso',
									'Burundi'=>'Burundi',
									'Camboya'=>'Camboya',
									'Camerun'=>'Camerun',
									'Canada'=>'Canada',
									'Cabo Verde'=>'Cabo Verde',
									'Islas Caiman'=>'Islas Caiman',
									'Republica Centroafricana'=>'Republica Centroafricana',
									'Chad'=>'Chad',
									'Chile'=>'Chile',
									'China'=>'China',
									'Isla de Navidad'=>'Isla de Navidad',
									'Islas Cocos (Keeling)'=>'Islas Cocos (Keeling)',
									'Colombia'=>'Colombia',
									'Comores'=>'Comores',
									'Congo'=>'Congo',
									'Islas Cook'=>'Islas Cook',
									'Costa Rica'=>'Costa Rica',
									'Croacia'=>'Croacia',
									'Cuba'=>'Cuba',
									'Chipre'=>'Chipre',
									'Republica Checa'=>'Republica Checa',
									'Republica Democratica del Congo'=>'Republica Democratica del Congo',
									'Dinamarca'=>'Dinamarca',
									'Territorio en disputa'=>'Territorio en disputa',
									'Djibouti'=>'Djibouti',
									'Dominica'=>'Dominica',
									'Republica Dominicana'=>'Republica Dominicana',
									'Timor Occidental'=>'Timor Occidental',
									'Ecuador'=>'Ecuador',
									'Egipto'=>'Egipto',
									'El Salvador'=>'El Salvador',
									'Guinea Ecuatorial'=>'Guinea Ecuatorial',
									'Eritrea'=>'Eritrea',
									'Estonia'=>'Estonia',
									'Etiopia'=>'Etiopia',
									'Islas Malvinas'=>'Islas Malvinas',
									'Islas Faroe'=>'Islas Faroe',
									'Estados Federados de Micronesia'=>'Estados Federados de Micronesia',
									'Fiji'=>'Fiji',
									'Finlandia'=>'Finlandia',
									'Francia'=>'Francia',
									'Guayana Francesa'=>'Guayana Francesa',
									'Polinesia Francesa'=>'Polinesia Francesa',
									'Territorios Franceses del Sur'=>'Territorios Franceses del Sur',
									'Gabon'=>'Gabon',
									'Gambia'=>'Gambia',
									'Georgia'=>'Georgia',
									'Alemania'=>'Alemania',
									'Ghana'=>'Ghana',
									'Gibraltar'=>'Gibraltar',
									'Grecia'=>'Grecia',
									'Groenlandia'=>'Groenlandia',
									'Grenada'=>'Grenada',
									'Guadalupe'=>'Guadalupe',
									'Guam'=>'Guam',
									'Guatemala'=>'Guatemala',
									'Guinea'=>'Guinea',
									'Guinea-Bissau'=>'Guinea-Bissau',
									'Guyana'=>'Guyana',
									'Haiti'=>'Haiti',
									'Islas Heard y McDonald'=>'Islas Heard y McDonald',
									'Honduras'=>'Honduras',
									'Hong Kong'=>'Hong Kong',
									'Hungria'=>'Hungria',
									'Islandia'=>'Islandia',
									'India'=>'India',
									'Indonesia'=>'Indonesia',
									'Iran'=>'Iran',
									'Iraq'=>'Iraq',
									'Zona neutra Iraq-Arabia Saudi'=>'Zona neutra Iraq-Arabia Saudi',
									'Irlanda'=>'Irlanda',
									'Israel'=>'Israel',
									'Italia'=>'Italia',
									'Costa de Marfil'=>'Costa de Marfil',
									'Jamaica'=>'Jamaica',
									'Japon'=>'Japon',
									'Jordania'=>'Jordania',
									'Kazajstan'=>'Kazajstan',
									'Kenia'=>'Kenia',
									'Kiribati'=>'Kiribati',
									'Kuwait'=>'Kuwait',
									'Kirguistan'=>'Kirguistan',
									'Laos'=>'Laos',
									'Letonia'=>'Letonia',
									'Libano'=>'Libano',
									'Lesotho'=>'Lesotho',
									'Liberia'=>'Liberia',
									'Libia'=>'Libia',
									'Liechtenstein'=>'Liechtenstein',
									'Lituania'=>'Lituania',
									'Luxemburgo'=>'Luxemburgo',
									'Macau'=>'Macau',
									'Macedonia'=>'Macedonia',
									'Madagascar'=>'Madagascar',
									'Malawi'=>'Malawi',
									'Malasia'=>'Malasia',
									'Maldivas'=>'Maldivas',
									'Mali'=>'Mali',
									'Malta'=>'Malta',
									'Islas Marshall'=>'Islas Marshall',
									'Martinica'=>'Martinica',
									'Mauritania'=>'Mauritania',
									'Mauricio'=>'Mauricio',
									'Mayotte'=>'Mayotte',
									'México'=>'México',
									'Moldova'=>'Moldova',
									'Monaco'=>'Monaco',
									'Mongolia'=>'Mongolia',
									'Montserrat'=>'Montserrat',
									'Marruecos'=>'Marruecos',
									'Mozambique'=>'Mozambique',
									'Myanmar'=>'Myanmar',
									'Namibia'=>'Namibia',
									'Nauru'=>'Nauru',
									'Nepal'=>'Nepal',
									'Paises Bajos'=>'Paises Bajos',
									'Antillas Holandesas'=>'Antillas Holandesas',
									'Nueva Caledonia'=>'Nueva Caledonia',
									'Nueva Zelanda'=>'Nueva Zelanda',
									'Nicaragua'=>'Nicaragua',
									'Niger'=>'Niger',
									'Nigeria'=>'Nigeria',
									'Niue'=>'Niue',
									'Isla Norfolk'=>'Isla Norfolk',
									'Corea del Norte'=>'Corea del Norte',
									'Islas Mariana del Norte'=>'Islas Mariana del Norte',
									'Noruega'=>'Noruega',
									'Oman'=>'Oman',
									'Pakistan'=>'Pakistan',
									'Palau'=>'Palau',
									'Territorios Palestinos Ocupados'=>'Territorios Palestinos Ocupados',
									'Panama'=>'Panama',
									'Papua-Nueva Guinea'=>'Papua-Nueva Guinea',
									'Paraguay'=>'Paraguay',
									'Peru'=>'Peru',
									'Filipinas'=>'Filipinas',
									'Islas Pitcairn'=>'Islas Pitcairn',
									'Polonia'=>'Polonia',
									'Portugal'=>'Portugal',
									'Puerto Rico'=>'Puerto Rico',
									'Qatar'=>'Qatar',
									'Reunion'=>'Reunion',
									'Rumania'=>'Rumania',
									'Rusia'=>'Rusia',
									'Ruanda'=>'Ruanda',
									'Santa Elena y Dependencias'=>'Santa Elena y Dependencias',
									'Saint Kitts y Nevis'=>'Saint Kitts y Nevis',
									'Santa Lucia'=>'Santa Lucia',
									'San Pedro y Miquelon'=>'San Pedro y Miquelon',
									'San Vicente y Granadinas'=>'San Vicente y Granadinas',
									'Samoa'=>'Samoa',
									'San Marino'=>'San Marino',
									'Santo Tomé y Principe'=>'Santo Tomé y Principe',
									'Arabia Saudi'=>'Arabia Saudi',
									'Senegal'=>'Senegal',
									'Serbia y Montenegro'=>'Serbia y Montenegro',
									'Seychelles'=>'Seychelles',
									'Sierra Leona'=>'Sierra Leona',
									'Singapur'=>'Singapur',
									'Eslovaquia'=>'Eslovaquia',
									'Eslovenia'=>'Eslovenia',
									'Islas Salomon'=>'Islas Salomon',
									'Somalia'=>'Somalia',
									'Sudafrica'=>'Sudafrica',
									'Islas Georgia del Sur e Islas Sandwich del Sur'=>'Islas Georgia del Sur e Islas Sandwich del Sur',
									'Corea del Sur'=>'Corea del Sur',
									'España'=>'España',
									'Islas Spratly'=>'Islas Spratly',
									'Sri Lanka'=>'Sri Lanka',
									'Sudan'=>'Sudan',
									'Surinam'=>'Surinam',
									'Islas Svalbard y Jan Mayen'=>'Islas Svalbard y Jan Mayen',
									'Swazilandia'=>'Swazilandia',
									'Suecia'=>'Suecia',
									'Suiza'=>'Suiza',
									'Siria'=>'Siria',
									'Taiwan'=>'Taiwan',
									'Tayikistan'=>'Tayikistan',
									'Tanzania'=>'Tanzania',
									'Tailandia'=>'Tailandia',
									'Togo'=>'Togo',
									'Tokelau'=>'Tokelau',
									'Tonga'=>'Tonga',
									'Trinidad y Tobago'=>'Trinidad y Tobago',
									'Tunez'=>'Tunez',
									'Turquia'=>'Turquia',
									'Turkmenistan'=>'Turkmenistan',
									'Islas Turks y Caicos'=>'Islas Turks y Caicos',
									'Tuvalu'=>'Tuvalu',
									'Uganda'=>'Uganda',
									'Ucrania'=>'Ucrania',
									'Emiratos arabes Unidos'=>'Emiratos arabes Unidos',
									'Reino Unido'=>'Reino Unido',
									'Zona neutra de las Naciones Unidas'=>'Zona neutra de las Naciones Unidas',
									'Estados Unidos'=>'Estados Unidos',
									'Islas Menores de los Estados Unidos'=>'Islas Menores de los Estados Unidos',
									'Uruguay'=>'Uruguay',
									'Islas Virgenes de los Estados Unidos'=>'Islas Virgenes de los Estados Unidos',
									'Uzbekistan'=>'Uzbekistan',
									'Vanuatu'=>'Vanuatu',
									'Vaticano'=>'Vaticano',
									'Venezuela'=>'Venezuela',
									'Vietnam'=>'Vietnam',
									'Wallis y Futuna'=>'Wallis y Futuna',
									'Sahara Occidental'=>'Sahara Occidental',
									'Yemen'=>'Yemen',
									'Zambia'=>'Zambia',
									'Zimbabwe'=>'Zimbabwe')
						)
						->setRequired(true);
		
		
		$institucion_origen = new Zend_Form_Element_Text('institucion_origen');
		$institucion_origen->setLabel('Institucion Origen')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$pais_destino = new Zend_Form_Element_Select('pais_destino');
		$pais_destino->setLabel('Pais Destino')
		->setDecorators($this->elementsDecorators)
		->setmultioptions(array('Afganistan'=>'Afganistan',
									'Islas Aland '=>'Islas Aland ',
									'Albania'=>'Albania',
									'Argelia'=>'Argelia',
									'Samoa Americana'=>'Samoa Americana',
									'Andorra'=>'Andorra',
									'Angola'=>'Angola',
									'Anguila'=>'Anguila',
									'Antartida'=>'Antartida',
									'Antigua y Barbuda'=>'Antigua y Barbuda',
									'Argentina'=>'Argentina',
									'Armenia'=>'Armenia',
									'Aruba'=>'Aruba',
									'Australia'=>'Australia',
									'Austria'=>'Austria',
									'Azerbaiyan'=>'Azerbaiyan',
									'Bahamas'=>'Bahamas',
									'Bahrein'=>'Bahrein',
									'Bangladesh'=>'Bangladesh',
									'Barbados'=>'Barbados',
									'Bielorusia'=>'Bielorusia',
									'Belgica'=>'Belgica',
									'Belice'=>'Belice',
									'Benin'=>'Benin',
									'Bermuda'=>'Bermuda',
									'Butan'=>'Butan',
									'Bolivia'=>'Bolivia',
									'Bosnia y Herzegovina'=>'Bosnia y Herzegovina',
									'Botswana'=>'Botswana',
									'Isla Bouvet'=>'Isla Bouvet',
									'Brasil'=>'Brasil',
									'Territorio Britanico en el Oceano Indico'=>'Territorio Britanico en el Oceano Indico',
									'Islas Virgenes (Reino Unido)'=>'Islas Virgenes (Reino Unido)',
									'Brunei'=>'Brunei',
									'Bulgaria'=>'Bulgaria',
									'Burkina Faso'=>'Burkina Faso',
									'Burundi'=>'Burundi',
									'Camboya'=>'Camboya',
									'Camerun'=>'Camerun',
									'Canada'=>'Canada',
									'Cabo Verde'=>'Cabo Verde',
									'Islas Caiman'=>'Islas Caiman',
									'Republica Centroafricana'=>'Republica Centroafricana',
									'Chad'=>'Chad',
									'Chile'=>'Chile',
									'China'=>'China',
									'Isla de Navidad'=>'Isla de Navidad',
									'Islas Cocos (Keeling)'=>'Islas Cocos (Keeling)',
									'Colombia'=>'Colombia',
									'Comores'=>'Comores',
									'Congo'=>'Congo',
									'Islas Cook'=>'Islas Cook',
									'Costa Rica'=>'Costa Rica',
									'Croacia'=>'Croacia',
									'Cuba'=>'Cuba',
									'Chipre'=>'Chipre',
									'Republica Checa'=>'Republica Checa',
									'Republica Democratica del Congo'=>'Republica Democratica del Congo',
									'Dinamarca'=>'Dinamarca',
									'Territorio en disputa'=>'Territorio en disputa',
									'Djibouti'=>'Djibouti',
									'Dominica'=>'Dominica',
									'Republica Dominicana'=>'Republica Dominicana',
									'Timor Occidental'=>'Timor Occidental',
									'Ecuador'=>'Ecuador',
									'Egipto'=>'Egipto',
									'El Salvador'=>'El Salvador',
									'Guinea Ecuatorial'=>'Guinea Ecuatorial',
									'Eritrea'=>'Eritrea',
									'Estonia'=>'Estonia',
									'Etiopia'=>'Etiopia',
									'Islas Malvinas'=>'Islas Malvinas',
									'Islas Faroe'=>'Islas Faroe',
									'Estados Federados de Micronesia'=>'Estados Federados de Micronesia',
									'Fiji'=>'Fiji',
									'Finlandia'=>'Finlandia',
									'Francia'=>'Francia',
									'Guayana Francesa'=>'Guayana Francesa',
									'Polinesia Francesa'=>'Polinesia Francesa',
									'Territorios Franceses del Sur'=>'Territorios Franceses del Sur',
									'Gabon'=>'Gabon',
									'Gambia'=>'Gambia',
									'Georgia'=>'Georgia',
									'Alemania'=>'Alemania',
									'Ghana'=>'Ghana',
									'Gibraltar'=>'Gibraltar',
									'Grecia'=>'Grecia',
									'Groenlandia'=>'Groenlandia',
									'Grenada'=>'Grenada',
									'Guadalupe'=>'Guadalupe',
									'Guam'=>'Guam',
									'Guatemala'=>'Guatemala',
									'Guinea'=>'Guinea',
									'Guinea-Bissau'=>'Guinea-Bissau',
									'Guyana'=>'Guyana',
									'Haiti'=>'Haiti',
									'Islas Heard y McDonald'=>'Islas Heard y McDonald',
									'Honduras'=>'Honduras',
									'Hong Kong'=>'Hong Kong',
									'Hungria'=>'Hungria',
									'Islandia'=>'Islandia',
									'India'=>'India',
									'Indonesia'=>'Indonesia',
									'Iran'=>'Iran',
									'Iraq'=>'Iraq',
									'Zona neutra Iraq-Arabia Saudi'=>'Zona neutra Iraq-Arabia Saudi',
									'Irlanda'=>'Irlanda',
									'Israel'=>'Israel',
									'Italia'=>'Italia',
									'Costa de Marfil'=>'Costa de Marfil',
									'Jamaica'=>'Jamaica',
									'Japon'=>'Japon',
									'Jordania'=>'Jordania',
									'Kazajstan'=>'Kazajstan',
									'Kenia'=>'Kenia',
									'Kiribati'=>'Kiribati',
									'Kuwait'=>'Kuwait',
									'Kirguistan'=>'Kirguistan',
									'Laos'=>'Laos',
									'Letonia'=>'Letonia',
									'Libano'=>'Libano',
									'Lesotho'=>'Lesotho',
									'Liberia'=>'Liberia',
									'Libia'=>'Libia',
									'Liechtenstein'=>'Liechtenstein',
									'Lituania'=>'Lituania',
									'Luxemburgo'=>'Luxemburgo',
									'Macau'=>'Macau',
									'Macedonia'=>'Macedonia',
									'Madagascar'=>'Madagascar',
									'Malawi'=>'Malawi',
									'Malasia'=>'Malasia',
									'Maldivas'=>'Maldivas',
									'Mali'=>'Mali',
									'Malta'=>'Malta',
									'Islas Marshall'=>'Islas Marshall',
									'Martinica'=>'Martinica',
									'Mauritania'=>'Mauritania',
									'Mauricio'=>'Mauricio',
									'Mayotte'=>'Mayotte',
									'México'=>'México',
									'Moldova'=>'Moldova',
									'Monaco'=>'Monaco',
									'Mongolia'=>'Mongolia',
									'Montserrat'=>'Montserrat',
									'Marruecos'=>'Marruecos',
									'Mozambique'=>'Mozambique',
									'Myanmar'=>'Myanmar',
									'Namibia'=>'Namibia',
									'Nauru'=>'Nauru',
									'Nepal'=>'Nepal',
									'Paises Bajos'=>'Paises Bajos',
									'Antillas Holandesas'=>'Antillas Holandesas',
									'Nueva Caledonia'=>'Nueva Caledonia',
									'Nueva Zelanda'=>'Nueva Zelanda',
									'Nicaragua'=>'Nicaragua',
									'Niger'=>'Niger',
									'Nigeria'=>'Nigeria',
									'Niue'=>'Niue',
									'Isla Norfolk'=>'Isla Norfolk',
									'Corea del Norte'=>'Corea del Norte',
									'Islas Mariana del Norte'=>'Islas Mariana del Norte',
									'Noruega'=>'Noruega',
									'Oman'=>'Oman',
									'Pakistan'=>'Pakistan',
									'Palau'=>'Palau',
									'Territorios Palestinos Ocupados'=>'Territorios Palestinos Ocupados',
									'Panama'=>'Panama',
									'Papua-Nueva Guinea'=>'Papua-Nueva Guinea',
									'Paraguay'=>'Paraguay',
									'Peru'=>'Peru',
									'Filipinas'=>'Filipinas',
									'Islas Pitcairn'=>'Islas Pitcairn',
									'Polonia'=>'Polonia',
									'Portugal'=>'Portugal',
									'Puerto Rico'=>'Puerto Rico',
									'Qatar'=>'Qatar',
									'Reunion'=>'Reunion',
									'Rumania'=>'Rumania',
									'Rusia'=>'Rusia',
									'Ruanda'=>'Ruanda',
									'Santa Elena y Dependencias'=>'Santa Elena y Dependencias',
									'Saint Kitts y Nevis'=>'Saint Kitts y Nevis',
									'Santa Lucia'=>'Santa Lucia',
									'San Pedro y Miquelon'=>'San Pedro y Miquelon',
									'San Vicente y Granadinas'=>'San Vicente y Granadinas',
									'Samoa'=>'Samoa',
									'San Marino'=>'San Marino',
									'Santo Tomé y Principe'=>'Santo Tomé y Principe',
									'Arabia Saudi'=>'Arabia Saudi',
									'Senegal'=>'Senegal',
									'Serbia y Montenegro'=>'Serbia y Montenegro',
									'Seychelles'=>'Seychelles',
									'Sierra Leona'=>'Sierra Leona',
									'Singapur'=>'Singapur',
									'Eslovaquia'=>'Eslovaquia',
									'Eslovenia'=>'Eslovenia',
									'Islas Salomon'=>'Islas Salomon',
									'Somalia'=>'Somalia',
									'Sudafrica'=>'Sudafrica',
									'Islas Georgia del Sur e Islas Sandwich del Sur'=>'Islas Georgia del Sur e Islas Sandwich del Sur',
									'Corea del Sur'=>'Corea del Sur',
									'España'=>'España',
									'Islas Spratly'=>'Islas Spratly',
									'Sri Lanka'=>'Sri Lanka',
									'Sudan'=>'Sudan',
									'Surinam'=>'Surinam',
									'Islas Svalbard y Jan Mayen'=>'Islas Svalbard y Jan Mayen',
									'Swazilandia'=>'Swazilandia',
									'Suecia'=>'Suecia',
									'Suiza'=>'Suiza',
									'Siria'=>'Siria',
									'Taiwan'=>'Taiwan',
									'Tayikistan'=>'Tayikistan',
									'Tanzania'=>'Tanzania',
									'Tailandia'=>'Tailandia',
									'Togo'=>'Togo',
									'Tokelau'=>'Tokelau',
									'Tonga'=>'Tonga',
									'Trinidad y Tobago'=>'Trinidad y Tobago',
									'Tunez'=>'Tunez',
									'Turquia'=>'Turquia',
									'Turkmenistan'=>'Turkmenistan',
									'Islas Turks y Caicos'=>'Islas Turks y Caicos',
									'Tuvalu'=>'Tuvalu',
									'Uganda'=>'Uganda',
									'Ucrania'=>'Ucrania',
									'Emiratos arabes Unidos'=>'Emiratos arabes Unidos',
									'Reino Unido'=>'Reino Unido',
									'Zona neutra de las Naciones Unidas'=>'Zona neutra de las Naciones Unidas',
									'Estados Unidos'=>'Estados Unidos',
									'Islas Menores de los Estados Unidos'=>'Islas Menores de los Estados Unidos',
									'Uruguay'=>'Uruguay',
									'Islas Virgenes de los Estados Unidos'=>'Islas Virgenes de los Estados Unidos',
									'Uzbekistan'=>'Uzbekistan',
									'Vanuatu'=>'Vanuatu',
									'Vaticano'=>'Vaticano',
									'Venezuela'=>'Venezuela',
									'Vietnam'=>'Vietnam',
									'Wallis y Futuna'=>'Wallis y Futuna',
									'Sahara Occidental'=>'Sahara Occidental',
									'Yemen'=>'Yemen',
									'Zambia'=>'Zambia',
									'Zimbabwe'=>'Zimbabwe')
						)
						->setRequired(true);
		
		
		$institucion_destino = new Zend_Form_Element_Text('institucion_destino');
		$institucion_destino->setLabel('Institucion de Destino')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$duracion = new Zend_Form_Element_Text('duracion');
		$duracion->setLabel('Duracion(Meses)')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$facultad_dependencia = new Zend_Form_Element_Text('facultad_dependencia');
		$facultad_dependencia->setLabel('Facultad / Dependencia')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
				
		$programa = new Zend_Form_Element_Text('programa');
		$programa->setLabel('Programa')
		->setDecorators($this->elementsDecorators)
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		
		$submit = new Zend_Form_Element_Submit('submit');
		$submit->setAttrib('id', 'submitbutton')
		->setDecorators($this->buttonsDecorators);
		
		$reset = new Zend_Form_Element_Reset('reset');
		$reset->setLabel('Cancelar')
		->setDecorators($this->buttonsDecorators)
		->setAttrib('onclick', 'history.back(-1);');
		
		
		$this->addElements(array($id, $idPersona, $ano, $periodo, $semestre, $pais_origen, $institucion_origen, $pais_destino, $institucion_destino, $duracion, $facultad_dependencia, $programa, $submit, $reset));
	}
}
?>