<p>¿Estás seguro que quieres borrar el Beneficio 
'<?php echo $this->escape($this->beneficio['nombre']); ?>' 
</p>
<form action="<?php echo $this->url(array('action'=>'borrar')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->beneficio['id']; ?>" />
		<input type="submit" name="del" value="Si" />
		<input type="submit" name="del" value="No" />
	</div>
</form>