<p><a href="<?php echo $this->url(array('controller'=>'beneficio','action'=>'agregar'));?>">A&ntilde;adir nuevo beneficio</a></p>
<table border="1" align="center"  width="100%" align="center" bordercolor="#999999" cellspacing="0">
	<tr>
		<th>Beneficio</th>
		
		<th>Acciones</th>
		
	</tr>
	<?php foreach($this->beneficio as $beneficio) : ?>
	<tr align="center">		
		<td><?php echo htmlentities($this->escape($beneficio->nombre)) ;?></td>
		
		<td>
			<a href="<?php echo $this->url(array('controller'=>'beneficio', 'action'=>'editar', 'id'=>$beneficio->id));?>">Editar</a>
			<a href="<?php echo $this->url(array('controller'=>'beneficio',	'action'=>'borrar', 'id'=>$beneficio->id));?>">Borrar</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>