<?php
class Form_Pasantia extends Zend_Form{

	public function __construct($options = null){
		parent::__construct($options);
		
		$this->setName('pasantia');
		 $id = new Zend_Form_Element_Hidden('id'); 
		 
		$idPersona = new Zend_Form_Element_Text('idPersona');
		$idPersona->setLabel('Persona Id')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$ano = new Zend_Form_Element_Text('ano');
		$ano->setLabel('Año')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$periodo = new Zend_Form_Element_Select('periodo');
		$periodo->setLabel('Periodo')
		->setmultioptions(array('I' =>'I', 'II'=>'II'))
		->setRequired(true);
		
		$semestre = new Zend_Form_Element_Select('semestre');
		$semestre->setLabel('Semestre')
		->setmultioptions(array('1' =>'I', '2'=>'II','3' =>'III', '4'=>'IV','5' =>'V', '6'=>'VI','7' =>'VII', '8'=>'VIII','9' =>'IX', '10'=>'X','NA' => 'NA'))
		->setRequired(true);
		
		$pais_origen = new Zend_Form_Element_Select('pais_origen');
		$pais_origen->setLabel('Pais de Origen')
		->setmultioptions(array('af' => 'Afganistán',
								 'ax' => 'Islas Aland ',
								 'al' => 'Albania',
								 'dz' => 'Argelia',
								 'as' => 'Samoa Americana',
								 'ad' => 'Andorra',
								 'ao' => 'Angola',
								 'ai' => 'Anguila',
								 'aq' => 'Antártida',
								 'ag' => 'Antigua y Barbuda',
								 'ar' => 'Argentina',
								 'am' => 'Armenia',
								 'aw' => 'Aruba',
								 'au' => 'Australia',
								 'at' => 'Austria',
								 'az' => 'Azerbaiyán',
								 'bs' => 'Bahamas',
								 'bh' => 'Bahréin',
								 'bd' => 'Bangladesh',
								 'bb' => 'Barbados',
								 'by' => 'Bielorusia',
								 'be' => 'Bélgica',
								 'bz' => 'Belice',
								 'bj' => 'Benin',
								 'bm' => 'Bermuda',
								 'bt' => 'Bután',
								 'bo' => 'Bolivia',
								 'ba' => 'Bosnia y Herzegovina',
								 'bw' => 'Botswana',
								 'bv' => 'Isla Bouvet',
								 'br' => 'Brasil',
								 'io' => 'Territorio Británico en el Océano Indico',
								 'vg' => 'Islas Vírgenes (Reino Unido)',
								 'bn' => 'Brunei',
								 'bg' => 'Bulgaria',
								 'bf' => 'Burkina Faso',
								 'bi' => 'Burundi',
								 'kh' => 'Camboya',
								 'cm' => 'Camerún',
								 'ca' => 'Canadá',
								 'cv' => 'Cabo Verde',
								 'ky' => 'Islas Caimán',
								 'cf' => 'República Centroafricana',
								 'td' => 'Chad',
								 'cl' => 'Chile',
								 'cn' => 'China',
								 'cx' => 'Isla de Navidad',
								 'cc' => 'Islas Cocos (Keeling)',
								 'co' => 'Colombia',
								 'km' => 'Comores',
								 'cg' => 'Congo',
								 'ck' => 'Islas Cook',
								 'cr' => 'Costa Rica',
								 'hr' => 'Croacia',
								 'cu' => 'Cuba',
								 'cy' => 'Chipre',
								 'cz' => 'República Checa',
								 'cd' => 'República Democrática del Congo',
								 'dk' => 'Dinamarca',
								 'xx' => 'Territorio en disputa',
								 'dj' => 'Djibouti',
								 'dm' => 'Dominica',
								 'do' => 'República Dominicana',
								 'tl' => 'Timor Occidental',
								 'ec' => 'Ecuador',
								 'eg' => 'Egipto',
								 'sv' => 'El Salvador',
								 'gq' => 'Guinea Ecuatorial',
								 'er' => 'Eritrea',
								 'ee' => 'Estonia',
								 'et' => 'Etiopía',
								 'fk' => 'Islas Malvinas',
								 'fo' => 'Islas Faroe',
								 'fm' => 'Estados Federados de Micronesia',
								 'fj' => 'Fiji',
								 'fi' => 'Finlandia',
								 'fr' => 'Francia',
								 'gf' => 'Guayana Francesa',
								 'pf' => 'Polinesia Francesa',
								 'tf' => 'Territorios Franceses del Sur',
								 'ga' => 'Gabón',
								 'gm' => 'Gambia',
								 'ge' => 'Georgia',
								 'de' => 'Alemania',
								 'gh' => 'Ghana',
								 'gi' => 'Gibraltar',
								 'gr' => 'Grecia',
								 'gl' => 'Groenlandia',
								 'gd' => 'Grenada',
								 'gp' => 'Guadalupe',
								 'gu' => 'Guam',
								 'gt' => 'Guatemala',
								 'gn' => 'Guinea',
								 'gw' => 'Guinea-Bissau',
								 'gy' => 'Guyana',
								 'ht' => 'Haití',
								 'hm' => 'Islas Heard y McDonald',
								 'hn' => 'Honduras',
								 'hk' => 'Hong Kong',
								 'hu' => 'Hungría',
								 'is' => 'Islandia',
								 'in' => 'India',
								 'id' => 'Indonesia',
								 'ir' => 'Irán',
								 'iq' => 'Iraq',
								 'xe' => 'Zona neutra Iraq-Arabia Saudí',
								 'ie' => 'Irlanda',
								 'il' => 'Israel',
								 'it' => 'Italia',
								 'ci' => 'Costa de Marfil',
								 'jm' => 'Jamaica',
								 'jp' => 'Japón',
								 'jo' => 'Jordania',
								 'kz' => 'Kazajstán',
								 'ke' => 'Kenia',
								 'ki' => 'Kiribati',
								 'kw' => 'Kuwait',
								 'kg' => 'Kirguistán',
								 'la' => 'Laos',
								 'lv' => 'Letonia',
								 'lb' => 'Líbano',
								 'ls' => 'Lesotho',
								 'lr' => 'Liberia',
								 'ly' => 'Libia',
								 'li' => 'Liechtenstein',
								 'lt' => 'Lituania',
								 'lu' => 'Luxemburgo',
								 'mo' => 'Macau',
								 'mk' => 'Macedonia',
								 'mg' => 'Madagascar',
								 'mw' => 'Malawi',
								 'my' => 'Malasia',
								 'mv' => 'Maldivas',
								 'ml' => 'Mali',
								 'mt' => 'Malta',
								 'mh' => 'Islas Marshall',
								 'mq' => 'Martinica',
								 'mr' => 'Mauritania',
								 'mu' => 'Mauricio',
								 'yt' => 'Mayotte',
								 'mx' => 'México',
								 'md' => 'Moldova',
								 'mc' => 'Mónaco',
								 'mn' => 'Mongolia',
								 'ms' => 'Montserrat',
								 'ma' => 'Marruecos',
								 'mz' => 'Mozambique',
								 'mm' => 'Myanmar',
								 'na' => 'Namibia',
								 'nr' => 'Nauru',
								 'np' => 'Nepal',
								 'nl' => 'Países Bajos',
								 'an' => 'Antillas Holandesas',
								 'nc' => 'Nueva Caledonia',
								 'nz' => 'Nueva Zelanda',
								 'ni' => 'Nicaragua',
								 'ne' => 'Níger',
								 'ng' => 'Nigeria',
								 'nu' => 'Niue',
								 'nf' => 'Isla Norfolk',
								 'kp' => 'Corea del Norte',
								 'mp' => 'Islas Mariana del Norte',
								 'no' => 'Noruega',
								 'om' => 'Omán',
								 'pk' => 'Pakistán',
								 'pw' => 'Palau',
								 'ps' => 'Territorios Palestinos Ocupados',
								 'pa' => 'Panamá',
								 'pg' => 'Papúa-Nueva Guinea',
								 'py' => 'Paraguay',
								 'pe' => 'Perú',
								 'ph' => 'Filipinas',
								 'pn' => 'Islas Pitcairn',
								 'pl' => 'Polonia',
								 'pt' => 'Portugal',
								 'pr' => 'Puerto Rico',
								 'qa' => 'Qatar',
								 're' => 'Reunión',
								 'ro' => 'Rumanía',
								 'ru' => 'Rusia',
								 'rw' => 'Ruanda',
								 'sh' => 'Santa Elena y Dependencias',
								 'kn' => 'Saint Kitts y Nevis',
								 'lc' => 'Santa Lucía',
								 'pm' => 'San Pedro y Miquelón',
								 'vc' => 'San Vicente y Granadinas',
								 'ws' => 'Samoa',
								 'sm' => 'San Marino',
								 'st' => 'Santo Tomé y Príncipe',
								 'sa' => 'Arabia Saudí',
								 'sn' => 'Senegal',
								 'cs' => 'Serbia y Montenegro',
								 'sc' => 'Seychelles',
								 'sl' => 'Sierra Leona',
								 'sg' => 'Singapur',
								 'sk' => 'Eslovaquia',
								 'si' => 'Eslovenia',
								 'sb' => 'Islas Salomón',
								 'so' => 'Somalia',
								 'za' => 'Sudáfrica',
								 'gs' => 'Islas Georgia del Sur e Islas Sandwich del Sur',
								 'kr' => 'Corea del Sur',
								 'es' => 'España',
								 'pi' => 'Islas Spratly',
								 'lk' => 'Sri Lanka',
								 'sd' => 'Sudán',
								 'sr' => 'Surinám',
								 'sj' => 'Islas Svalbard y Jan Mayen',
								 'sz' => 'Swazilandia',
								 'se' => 'Suecia',
								 'ch' => 'Suiza',
								 'sy' => 'Siria',
								 'tw' => 'Taiwán',
								 'tj' => 'Tayikistán',
								 'tz' => 'Tanzania',
								 'th' => 'Tailandia',
								 'tg' => 'Togo',
								 'tk' => 'Tokelau',
								 'to' => 'Tonga',
								 'tt' => 'Trinidad y Tobago',
								 'tn' => 'Túnez',
								 'tr' => 'Turquía',
								 'tm' => 'Turkmenistán',
								 'tc' => 'Islas Turks y Caicos',
								 'tv' => 'Tuvalu',
								 'ug' => 'Uganda',
								 'ua' => 'Ucrania',
								 'ae' => 'Emiratos Árabes Unidos',
								 'uk' => 'Reino Unido',
								 'xd' => 'Zona neutra de las Naciones Unidas',
								 'us' => 'Estados Unidos',
								 'um' => 'Islas Menores de los Estados Unidos',
								 'uy' => 'Uruguay',
								 'vi' => 'Islas Vírgenes de los Estados Unidos',
								 'uz' => 'Uzbekistán',
								 'vu' => 'Vanuatu',
								 'va' => 'Vaticano',
								 've' => 'Venezuela',
								 'vn' => 'Vietnám',
								 'wf' => 'Wallis y Futuna',
								 'eh' => 'Sáhara Occidental',
								 'ye' => 'Yemen',
								 'zm' => 'Zambia',
								 'zw' => 'Zimbabwe')
						)
						->setRequired(true);
		
		
		$institucion_origen = new Zend_Form_Element_Text('institucion_origen');
		$institucion_origen->setLabel('Institucion Origen')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$pais_destino = new Zend_Form_Element_Select('pais_destino');
		$pais_destino->setLabel('Pais Destino')
		->setmultioptions(array('af' => 'Afganistán',
								 'ax' => 'Islas Aland ',
								 'al' => 'Albania',
								 'dz' => 'Argelia',
								 'as' => 'Samoa Americana',
								 'ad' => 'Andorra',
								 'ao' => 'Angola',
								 'ai' => 'Anguila',
								 'aq' => 'Antártida',
								 'ag' => 'Antigua y Barbuda',
								 'ar' => 'Argentina',
								 'am' => 'Armenia',
								 'aw' => 'Aruba',
								 'au' => 'Australia',
								 'at' => 'Austria',
								 'az' => 'Azerbaiyán',
								 'bs' => 'Bahamas',
								 'bh' => 'Bahréin',
								 'bd' => 'Bangladesh',
								 'bb' => 'Barbados',
								 'by' => 'Bielorusia',
								 'be' => 'Bélgica',
								 'bz' => 'Belice',
								 'bj' => 'Benin',
								 'bm' => 'Bermuda',
								 'bt' => 'Bután',
								 'bo' => 'Bolivia',
								 'ba' => 'Bosnia y Herzegovina',
								 'bw' => 'Botswana',
								 'bv' => 'Isla Bouvet',
								 'br' => 'Brasil',
								 'io' => 'Territorio Británico en el Océano Indico',
								 'vg' => 'Islas Vírgenes (Reino Unido)',
								 'bn' => 'Brunei',
								 'bg' => 'Bulgaria',
								 'bf' => 'Burkina Faso',
								 'bi' => 'Burundi',
								 'kh' => 'Camboya',
								 'cm' => 'Camerún',
								 'ca' => 'Canadá',
								 'cv' => 'Cabo Verde',
								 'ky' => 'Islas Caimán',
								 'cf' => 'República Centroafricana',
								 'td' => 'Chad',
								 'cl' => 'Chile',
								 'cn' => 'China',
								 'cx' => 'Isla de Navidad',
								 'cc' => 'Islas Cocos (Keeling)',
								 'co' => 'Colombia',
								 'km' => 'Comores',
								 'cg' => 'Congo',
								 'ck' => 'Islas Cook',
								 'cr' => 'Costa Rica',
								 'hr' => 'Croacia',
								 'cu' => 'Cuba',
								 'cy' => 'Chipre',
								 'cz' => 'República Checa',
								 'cd' => 'República Democrática del Congo',
								 'dk' => 'Dinamarca',
								 'xx' => 'Territorio en disputa',
								 'dj' => 'Djibouti',
								 'dm' => 'Dominica',
								 'do' => 'República Dominicana',
								 'tl' => 'Timor Occidental',
								 'ec' => 'Ecuador',
								 'eg' => 'Egipto',
								 'sv' => 'El Salvador',
								 'gq' => 'Guinea Ecuatorial',
								 'er' => 'Eritrea',
								 'ee' => 'Estonia',
								 'et' => 'Etiopía',
								 'fk' => 'Islas Malvinas',
								 'fo' => 'Islas Faroe',
								 'fm' => 'Estados Federados de Micronesia',
								 'fj' => 'Fiji',
								 'fi' => 'Finlandia',
								 'fr' => 'Francia',
								 'gf' => 'Guayana Francesa',
								 'pf' => 'Polinesia Francesa',
								 'tf' => 'Territorios Franceses del Sur',
								 'ga' => 'Gabón',
								 'gm' => 'Gambia',
								 'ge' => 'Georgia',
								 'de' => 'Alemania',
								 'gh' => 'Ghana',
								 'gi' => 'Gibraltar',
								 'gr' => 'Grecia',
								 'gl' => 'Groenlandia',
								 'gd' => 'Grenada',
								 'gp' => 'Guadalupe',
								 'gu' => 'Guam',
								 'gt' => 'Guatemala',
								 'gn' => 'Guinea',
								 'gw' => 'Guinea-Bissau',
								 'gy' => 'Guyana',
								 'ht' => 'Haití',
								 'hm' => 'Islas Heard y McDonald',
								 'hn' => 'Honduras',
								 'hk' => 'Hong Kong',
								 'hu' => 'Hungría',
								 'is' => 'Islandia',
								 'in' => 'India',
								 'id' => 'Indonesia',
								 'ir' => 'Irán',
								 'iq' => 'Iraq',
								 'xe' => 'Zona neutra Iraq-Arabia Saudí',
								 'ie' => 'Irlanda',
								 'il' => 'Israel',
								 'it' => 'Italia',
								 'ci' => 'Costa de Marfil',
								 'jm' => 'Jamaica',
								 'jp' => 'Japón',
								 'jo' => 'Jordania',
								 'kz' => 'Kazajstán',
								 'ke' => 'Kenia',
								 'ki' => 'Kiribati',
								 'kw' => 'Kuwait',
								 'kg' => 'Kirguistán',
								 'la' => 'Laos',
								 'lv' => 'Letonia',
								 'lb' => 'Líbano',
								 'ls' => 'Lesotho',
								 'lr' => 'Liberia',
								 'ly' => 'Libia',
								 'li' => 'Liechtenstein',
								 'lt' => 'Lituania',
								 'lu' => 'Luxemburgo',
								 'mo' => 'Macau',
								 'mk' => 'Macedonia',
								 'mg' => 'Madagascar',
								 'mw' => 'Malawi',
								 'my' => 'Malasia',
								 'mv' => 'Maldivas',
								 'ml' => 'Mali',
								 'mt' => 'Malta',
								 'mh' => 'Islas Marshall',
								 'mq' => 'Martinica',
								 'mr' => 'Mauritania',
								 'mu' => 'Mauricio',
								 'yt' => 'Mayotte',
								 'mx' => 'México',
								 'md' => 'Moldova',
								 'mc' => 'Mónaco',
								 'mn' => 'Mongolia',
								 'ms' => 'Montserrat',
								 'ma' => 'Marruecos',
								 'mz' => 'Mozambique',
								 'mm' => 'Myanmar',
								 'na' => 'Namibia',
								 'nr' => 'Nauru',
								 'np' => 'Nepal',
								 'nl' => 'Países Bajos',
								 'an' => 'Antillas Holandesas',
								 'nc' => 'Nueva Caledonia',
								 'nz' => 'Nueva Zelanda',
								 'ni' => 'Nicaragua',
								 'ne' => 'Níger',
								 'ng' => 'Nigeria',
								 'nu' => 'Niue',
								 'nf' => 'Isla Norfolk',
								 'kp' => 'Corea del Norte',
								 'mp' => 'Islas Mariana del Norte',
								 'no' => 'Noruega',
								 'om' => 'Omán',
								 'pk' => 'Pakistán',
								 'pw' => 'Palau',
								 'ps' => 'Territorios Palestinos Ocupados',
								 'pa' => 'Panamá',
								 'pg' => 'Papúa-Nueva Guinea',
								 'py' => 'Paraguay',
								 'pe' => 'Perú',
								 'ph' => 'Filipinas',
								 'pn' => 'Islas Pitcairn',
								 'pl' => 'Polonia',
								 'pt' => 'Portugal',
								 'pr' => 'Puerto Rico',
								 'qa' => 'Qatar',
								 're' => 'Reunión',
								 'ro' => 'Rumanía',
								 'ru' => 'Rusia',
								 'rw' => 'Ruanda',
								 'sh' => 'Santa Elena y Dependencias',
								 'kn' => 'Saint Kitts y Nevis',
								 'lc' => 'Santa Lucía',
								 'pm' => 'San Pedro y Miquelón',
								 'vc' => 'San Vicente y Granadinas',
								 'ws' => 'Samoa',
								 'sm' => 'San Marino',
								 'st' => 'Santo Tomé y Príncipe',
								 'sa' => 'Arabia Saudí',
								 'sn' => 'Senegal',
								 'cs' => 'Serbia y Montenegro',
								 'sc' => 'Seychelles',
								 'sl' => 'Sierra Leona',
								 'sg' => 'Singapur',
								 'sk' => 'Eslovaquia',
								 'si' => 'Eslovenia',
								 'sb' => 'Islas Salomón',
								 'so' => 'Somalia',
								 'za' => 'Sudáfrica',
								 'gs' => 'Islas Georgia del Sur e Islas Sandwich del Sur',
								 'kr' => 'Corea del Sur',
								 'es' => 'España',
								 'pi' => 'Islas Spratly',
								 'lk' => 'Sri Lanka',
								 'sd' => 'Sudán',
								 'sr' => 'Surinám',
								 'sj' => 'Islas Svalbard y Jan Mayen',
								 'sz' => 'Swazilandia',
								 'se' => 'Suecia',
								 'ch' => 'Suiza',
								 'sy' => 'Siria',
								 'tw' => 'Taiwán',
								 'tj' => 'Tayikistán',
								 'tz' => 'Tanzania',
								 'th' => 'Tailandia',
								 'tg' => 'Togo',
								 'tk' => 'Tokelau',
								 'to' => 'Tonga',
								 'tt' => 'Trinidad y Tobago',
								 'tn' => 'Túnez',
								 'tr' => 'Turquía',
								 'tm' => 'Turkmenistán',
								 'tc' => 'Islas Turks y Caicos',
								 'tv' => 'Tuvalu',
								 'ug' => 'Uganda',
								 'ua' => 'Ucrania',
								 'ae' => 'Emiratos Árabes Unidos',
								 'uk' => 'Reino Unido',
								 'xd' => 'Zona neutra de las Naciones Unidas',
								 'us' => 'Estados Unidos',
								 'um' => 'Islas Menores de los Estados Unidos',
								 'uy' => 'Uruguay',
								 'vi' => 'Islas Vírgenes de los Estados Unidos',
								 'uz' => 'Uzbekistán',
								 'vu' => 'Vanuatu',
								 'va' => 'Vaticano',
								 've' => 'Venezuela',
								 'vn' => 'Vietnám',
								 'wf' => 'Wallis y Futuna',
								 'eh' => 'Sáhara Occidental',
								 'ye' => 'Yemen',
								 'zm' => 'Zambia',
								 'zw' => 'Zimbabwe')
						)
						->setRequired(true);
		
		
		$institucion_destino = new Zend_Form_Element_Text('institucion_destino');
		$institucion_destino->setLabel('Institucion de Destino')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$duracion = new Zend_Form_Element_Text('duracion');
		$duracion->setLabel('Duracion(Meses)')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		$facultad_dependencia = new Zend_Form_Element_Text('facultad_dependencia');
		$facultad_dependencia->setLabel('Facultad / Dependencia')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
				
		$programa = new Zend_Form_Element_Text('programa');
		$programa->setLabel('Programa')
		->setRequired(true)
		->addFilter('StripTags')
		->addFilter('StringTrim')
		->addValidator('NotEmpty');
		
		
		$submit = new Zend_Form_Element_Submit('submit');
		$submit->setAttrib('id', 'submitbutton');
		
		$cancel = new Zend_Form_Element_Button('Cancel');
		
		$this->addElements(array($id, $idPersona, $ano, $periodo, $semestre, $pais_origen, $institucion_origen, $pais_destino, $institucion_destino, $duracion, $facultad_dependencia, $programa));
	}
}
?>